### ISSUE TITLE
[JENKINS-73753] Modern Status incompatible with Jenkins 2.462.2

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/modernstatus-plugin#16]
<p>Modern Status plugin v1.3 fails to install/load in Jenkins 2.462.2 and encounters the error:</p>

```
WARNING [Loading plugin Modern Status v1.3 (modernstatus)] jenkins.model.Jenkins$5.runTask Loading plugin Modern Status v1.3 (modernstatus) failed perhaps due to plugin dependency issues
    java.io.IOException: Failed to initialize
        at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:403)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:556)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:177)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1175)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
    Caused by: java.lang.NoSuchMethodError: 'void hudson.util.PluginServletFilter.addFilter(javax.servlet.Filter)'
        at PluginClassLoader for modernstatus//org.jenkinsci.plugins.modernstatus.PluginImpl.start(PluginImpl.java:33)
        at hudson.ClassicPluginStrategy.startPlugin(ClassicPluginStrategy.java:411)
        at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:400)
        ... 10 more

```

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dcole1">dcole1</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-73753" target="_blank">Modern Status incompatible with Jenkins 2.462.2</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: modernstatus-plugin
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2024-09-10T19:51:01+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 20251223-222157
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Modern Status plugin v1.3 fails to install/load in Jenkins 2.462.2 and encounters the error:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>WARNING [Loading plugin Modern Status v1.3 (modernstatus)] jenkins.model.Jenkins$5.runTask Loading plugin Modern Status v1.3 (modernstatus) failed perhaps due to plugin dependency issues
    java.io.IOException: Failed to initialize
        at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:403)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:556)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:177)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1175)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
    Caused by: java.lang.NoSuchMethodError: 'void hudson.util.PluginServletFilter.addFilter(javax.servlet.Filter)'
        at PluginClassLoader for modernstatus//org.jenkinsci.plugins.modernstatus.PluginImpl.start(PluginImpl.java:33)
        at hudson.ClassicPluginStrategy.startPlugin(ClassicPluginStrategy.java:411)
        at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:400)
        ... 10 more
</pre>
</div></div></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.462.2, Tomcat 10.1, OpenJDK 21<br/>
Modern Status v1.3
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>basil:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-73753?focusedId=449226&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-449226">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dcole1" class="user-hover" rel="dcole1">dcole1</a> Please refer to our <a href="https://www.jenkins.io/doc/book/platform-information/support-policy-servlet-containers/" class="external-link" target="_blank" rel="nofollow noopener">Servlet Container Support Policy</a>. Tomcat 10 or later, based on Servlet API 5.0 (Jakarta EE 9) or later with <tt>jakarta.servlet</tt> imports, will only work on the Jenkins 2.475 weekly release or later (not scheduled for LTS until later in October).</p>
</pre>
</details>

</ul>
</details>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dcole1" class="user-hover" rel="dcole1">dcole1</a> Please refer to our <a href="https://www.jenkins.io/doc/book/platform-information/support-policy-servlet-containers/" class="external-link" target="_blank" rel="nofollow noopener">Servlet Container Support Policy</a>. Tomcat 10 or later, based on Servlet API 5.0 (Jakarta EE 9) or later with <tt>jakarta.servlet</tt> imports, will only work on the Jenkins 2.475 weekly release or later (not scheduled for LTS until later in October).</p>
