### ISSUE TITLE
Fails on Jenkins 2.579+: NoClassDefFoundError org/apache/commons/lang/StringUtils

### ISSUE THREAD

**Issue by jav-12** [jenkinsci/modernstatus-plugin#18]
After upgrading Jenkins from 2.577 to 2.579, Jenkins UI requests fail with the generic error page:

```
A problem occurred while processing the request
Logging ID=8c790aaf-dfbe-4161-ab30-a5db7c29ef08
```

The Jenkins service stays active, but affected UI requests fail. Jenkins logs show the failure comes from Modern Status:

```
Caught unhandled exception with ID 8c790aaf-dfbe-4161-ab30-a5db7c29ef08
Caused: java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
...
at PluginClassLoader for modernstatus//org.jenkinsci.plugins.modernstatus.ModernStatusFilter.doFilter(ModernStatusFilter.java:50)
```

Environment:

- Jenkins core: 2.579
- Previous Jenkins core: 2.577
- Java: 21
- Modern Status plugin: 1.3
- Installation type: Debian Jenkins package

Expected behavior:

Modern Status should work on Jenkins 2.579+ or declare/bundle the dependency it needs.

Actual behavior:

Jenkins UI requests can fail with `NoClassDefFoundError: org/apache/commons/lang/StringUtils` until the plugin is disabled.

Workaround:

```bash
touch /var/lib/jenkins/plugins/modernstatus.jpi.disabled
systemctl restart jenkins
```

Context:

Jenkins 2.579 intentionally removed Apache Commons Lang 2 from Jenkins core:
https://www.jenkins.io/changelog/2.579/

The changelog says outdated plugins that depended on Commons Lang 2 from Jenkins core may fail after the upgrade. Modern Status appears to be one of those plugins.
